image: andipeter/monogame-test:0.4

stages:
    - build
    - test
    - generate-docs
    - deploy

build:
    stage: build
    script:
        - dotnet build src/SpaceVsInvaders/

test:
    stage: test
    script:
        - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info src/SpaceVsInvaders.Tests/
        - reportgenerator "-reports:src/SpaceVsInvaders.Tests/lcov.info" "-targetdir:coveragereport" -reporttypes:Html
    artifacts:
        paths:
            - coveragereport
