image: andipeter/monogame-test:0.4

stages:
    - build
    - test
    - generate-docs
    - deploy

build:
    stage: build
    script:
        - dotnet build src/SpaceVsInvaders/

test:
    stage: test
    script:
        - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info src/SpaceVsInvaders.Tests/
        - reportgenerator "-reports:src/SpaceVsInvaders.Tests/lcov.info" "-targetdir:coveragereport" -reporttypes:Html
    artifacts:
        paths:
            - coveragereport

generate-docs:
    stage: generate-docs
    script:
        - mono /opt/docsfx.exe build $PWD/docs/webdocs/docfx.json
    artifacts:
        paths:
            - docs/webdocs/_site

pages:
    stage: deploy
    script:
        - cp -r coveragereport/ public/coveragereport/
        - cp -r docs/webdocs/_site/ public/docs/
    needs:
        - job: test
          artifacts: true
        - job: generate-docs
          artifacts: true
    artifacts:
        paths:
            - public
    
